//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testTensileMachineGraphics.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\kidalicaMetal\\ZbirniIzvestaji\\")]
        public string SumReportDir {
            get {
                return ((string)(this["SumReportDir"]));
            }
            set {
                this["SumReportDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\kidalicaMetal\\online.txt")]
        public string onlineFilepath {
            get {
                return ((string)(this["onlineFilepath"]));
            }
            set {
                this["onlineFilepath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\kidalicaMetal\\e2e4Online.e2e4")]
        public string e2e4Filepath {
            get {
                return ((string)(this["e2e4Filepath"]));
            }
            set {
                this["e2e4Filepath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\kidalicaMetal\\ulazIzlazOnline.inputoutput")]
        public string inputOutputFilepath {
            get {
                return ((string)(this["inputOutputFilepath"]));
            }
            set {
                this["inputOutputFilepath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\kidalicaMetal\\izvestajOnline.xml")]
        public string sampleReportFilepath {
            get {
                return ((string)(this["sampleReportFilepath"]));
            }
            set {
                this["sampleReportFilepath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\kidalicaMetal\\izvestajGrafikOnline.png")]
        public string sampleReportGraphicFilepath {
            get {
                return ((string)(this["sampleReportGraphicFilepath"]));
            }
            set {
                this["sampleReportGraphicFilepath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\kidalicaMetal\\izvestajGrafikOnlinePromenaR.png")]
        public string sampleReportGraphicFilepathChangeOfR {
            get {
                return ((string)(this["sampleReportGraphicFilepathChangeOfR"]));
            }
            set {
                this["sampleReportGraphicFilepathChangeOfR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\kidalicaMetal\\izvestajGrafikOnlinePromenaE.png")]
        public string sampleReportGraphicFilepathChangeOfE {
            get {
                return ((string)(this["sampleReportGraphicFilepathChangeOfE"]));
            }
            set {
                this["sampleReportGraphicFilepathChangeOfE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\kidalicaMetal\\nezapamceno.txt")]
        public string unsavedFilepath {
            get {
                return ((string)(this["unsavedFilepath"]));
            }
            set {
                this["unsavedFilepath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\kidalicaMetal\\Arhiva\\")]
        public string SaveDirectory {
            get {
                return ((string)(this["SaveDirectory"]));
            }
            set {
                this["SaveDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\kidalicaMetal\\PojedinacniIzvestaji\\")]
        public string SaveDirectoryForReports {
            get {
                return ((string)(this["SaveDirectoryForReports"]));
            }
            set {
                this["SaveDirectoryForReports"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\kidalicaMetal\\nezapamceno.pe")]
        public string unsavedFilepathPreassureElongation {
            get {
                return ((string)(this["unsavedFilepathPreassureElongation"]));
            }
            set {
                this["unsavedFilepathPreassureElongation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\kidalicaMetal\\ZbirniIzvestaji\\")]
        public string PATHOFSUMREPORT {
            get {
                return ((string)(this["PATHOFSUMREPORT"]));
            }
            set {
                this["PATHOFSUMREPORT"] = value;
            }
        }
    }
}
